Traceback (most recent call last):
  File "/home/calvo/alx-system_engineering-devops/0x15-api/0-gather_data_from_an_API.py", line 8, in <module>
    user = requests.get(url + "users/{}".format(sys.argv[1])).json()
IndexError: list index out of range
